const
    menuBarCon = document.querySelector('section.menu-bar-container'),
    mdjdIcon = document.querySelector('.mdjd-icon'),
    menuIcon = document.querySelector('.menu-icon'),
    rightMenuDiv = document.querySelector('.right-menu'),
    onAll = document.querySelector('.on-all'),
    categoryItems = document.querySelectorAll('.category-item'),
    lessons = document.querySelectorAll('.lesson'),
    searchInp = document.querySelector('input#mySearch'),
    searchInpInDiv = document.querySelector('div.search-div input[type=search]'),
    searchDiv = document.querySelector('div.search-div'),
    backOfSearch = document.querySelector('i.fa-arrow-right-long'),
    openSearchInp = document.querySelector('#openSearchInp'),
    profileIcon = document.querySelector('div.profile-icon'),
    profileBox = document.querySelector('div.profil-box-items'),
    onAll2 = document.querySelector('.user-bar-container .onAll2'),
    onAll3 = document.querySelector('.user-bar-container .onAll3'),
    onAll4 = document.querySelector('.onAll4'),
    cartIcon = document.querySelector('div.cart-icon'),
    cartBoxItems = document.querySelector('div.cart-box-items'),
    cartOutNum = document.querySelector('div.num-count-products output'),
    cityBox = document.querySelector('div.city-box'),
    itemsCityBox = document.querySelector('div.items-city-box ul'),
    AddressDiv = document.querySelector('select-address'),
    AddressDiv2 = document.querySelector('div.left-list'),
    addAddress = document.querySelector('li.add-item-city'),
    IcCloseAddBox = document.querySelector('div.city-box i.fa-close'),
    addAddressForm = document.querySelector('div.addAddressForm'),
    iCAddressF = document.querySelector('div.addAddressForm i.fa-close'),
    addressBtn = document.querySelector('div.addAddressForm footer button'),
    closeAddressBtn = document.querySelector('div.city-box i.fa-close'),
    supportBox = document.querySelector('div.question-box'),
    questionIcon = document.querySelector('div.question-icon'),
    questionItems = document.querySelectorAll('div.box-container div.question-item'),
    downQIcons = document.querySelectorAll('div.box-container i.fa-angle-down'),
    backIconQuestion = document.querySelector('div.header-q-box i.fa-arrow-left-long'),
    formBoxQuestion = document.querySelector('div.form-box-question'),
    openFQBtn = document.querySelector('#openFQBtn'),
    sendFQBtn = document.querySelector('#sendFQBtn'),
    questionFormFname = document.forms.questionForm.fName,
    questionFormPhoneNumber = document.forms.questionForm.phoneNumber,
    questionFormEmailAd = document.forms.questionForm.emailAd,
    questionFormTextarea = document.forms.questionForm.questionText,
    NumCharEnter = document.querySelector('#numCharEnter'),
    formLabels = document.querySelectorAll('form[name = questionForm] label'),
    ulProduct = document.querySelector('div.shegeftProducts ul'),
    imgsSlider = document.querySelector('div.images-slider'),
    btnsSlide = document.querySelector('div.buttons-slide'),
    pointsSlider = document.querySelector('div.points-slider'),
    itemsHL = document.querySelectorAll('li.item-header-list'),
    redHover = document.querySelector('div.redHover'),
    boxMega = document.querySelector('div.box-mega'),
    categoryIB = document.querySelector('div.categoryItemBtn'),
    leftList = document.querySelector('div.left-list'),
    searchBoxPc = document.querySelector('div.search-box-pc'),
    searchInpPc = document.querySelector('input[type = text]#searchInpPc'),
    searchPcUls = document.querySelectorAll('div.scroll-bg ul'),
    newst = document.querySelectorAll('div.newst main div.gridDis'),
    cellest = document.querySelectorAll('div.cellest main div.gridDis'),
    backToTop = document.querySelector('div.backToTop'),
    onAll5 = document.querySelector('div.onAll5');
export {
    mdjdIcon, menuIcon, rightMenuDiv, onAll, categoryItems,
    lessons, searchInp, searchDiv, backOfSearch, profileIcon,
    profileBox, onAll2, cartIcon, cartBoxItems, onAll3, onAll4,
    cityBox, AddressDiv, closeAddressBtn, supportBox, questionIcon,
    backIconQuestion, questionItems, downQIcons, formBoxQuestion,
    openFQBtn, sendFQBtn, questionFormFname, questionFormPhoneNumber,
    questionFormEmailAd, questionFormTextarea, NumCharEnter, formLabels,
    ulProduct, imgsSlider, btnsSlide, pointsSlider, itemsHL, redHover,
    boxMega, categoryIB, leftList, AddressDiv2, searchBoxPc,
    searchInpPc, onAll5, menuBarCon, searchInpInDiv, searchPcUls,
    openSearchInp, addAddress, addAddressForm, iCAddressF, addressBtn,
    itemsCityBox, IcCloseAddBox, cartOutNum, newst, cellest, backToTop
};